#debug: true
server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proyecto2
    username: postgres
    password: 2202
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  secret: abvfsljfvbsljfvbjlvbsjlvbsdxhsggdasgdhfjgfyigiyfuytdtdytdtydytdytddhdftdftdytdyrdyttdytdtydytdytd
springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
  path: /swagger-ui.html

